name: 'Auto label (fdaciuk test)'
description: 'issue creator can check their own labels'
author: 'fdaciuk'
branding:
  icon: 'check-square'
  color: 'blue'
inputs: 
  repo-token:
    description: 'github token for the repository'
    required: true
  ignore-comments:
    description: 'ignore labels inside issue comments'
    default: true
  labels-not-allowed:
    description: 'ignore labels'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
